theme: minima
title: Bootcamp Blog
author: Andrew Mills
email: awmills25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my bootcamp blog that will follow my path in learning to code!

# social links
twitter_username: @a_mills25 # DO NOT include the @ character, or else the build will fail!
github_username:  amills25 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
